kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: worker
    extraMounts:
      - hostPath: /data/development/hyperledger
        containerPath: /mnt/hyperledger
  - role: control-plane
    extraMounts:
      - hostPath: /data/developmen/hyperledger
        containerPath: /mnt/hyperledger
