kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: worker
    extraMounts:
      - hostPath: C:/Program Files/Git/data/experimental/hyperledger
        containerPath: /mnt/hyperledger
  - role: control-plane
    extraMounts:
      - hostPath: C:/Program Files/Git/data/experimental/hyperledger
        containerPath: /mnt/hyperledger
