apiVersion: batch/v1
kind: Job
metadata:
  name: enroll-peers-org1
  namespace: hlf
  labels:
    app: enroll-peers
spec:
  template:
    spec:
      containers:
        - name: fabric-ca
          image: hyperledger/fabric-ca:1.4.7
          imagePullPolicy: IfNotPresent
          command: ["bash", "./tmp/hyperledger/scripts/startNetwork/enrollJobs/enrollPeersOrg1.sh"]
          volumeMounts:
            - mountPath: /tmp/hyperledger/scripts
              name: scripts
            - mountPath: /tmp/hyperledger/org1
              name: org1-mount
            - mountPath: /tmp/secrets/tls-ca
              name: tls-ca-cert
              readOnly: true
            - mountPath: /tmp/secrets/rca-org1
              name: rca-org1-cert
              readOnly: true
          env:
            - name: FABRIC_CA_SERVER_DEBUG
              value: "true"
      volumes:
        - name: org1-mount
          hostPath:
            path: /mnt/hyperledger/org1
        - name: scripts
          hostPath:
            path: /mnt/hyperledger/scripts
        - name: tls-ca-cert
          secret:
            secretName: cert.tls-ca
        - name: rca-org1-cert
          secret:
            secretName: cert.rca-org1
      restartPolicy: Never
