kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: hlf
  name: rca-org1-pv
  labels:
    app: rca-org1
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/hyperledger/storage/rca-org1"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: hlf
  name: rca-org1-pvc
  labels:
    app: rca-org1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
