apiVersion: apps/v1
kind: Deployment
metadata:
    name: rca-org1
    namespace: hlf
    labels:
        app: rca-org1
spec:
    selector:
        matchLabels:
            app: rca-org1
    template:
        metadata: 
            labels:
                app: rca-org1
        spec:
            containers:
              - name: rca-org1
                image: hyperledger/fabric-ca:1.4.7
                imagePullPolicy: IfNotPresent
                command: ["fabric-ca-server", "start", "-b", "rca-org1-admin:rca-org1-adminpw", "--port", "7054"]
                volumeMounts:
                  - mountPath: /tmp/hyperledger/scripts
                    name: scripts
                  - mountPath: /tmp/secrets/cert.pem
                    name: cert
                    subPath: cert.pem
                    readOnly: true
                  - mountPath: /tmp/secrets/key.pem
                    name: key
                    subPath: key.pem
                    readOnly: true
                env:
                - name: FABRIC_CA_HOME
                  value: "/tmp/hyperledger/fabric-ca/crypto"
                - name: FABRIC_CA_SERVER_TLS_ENABLED
                  value: "true"
                - name: FABRIC_CA_SERVER_CSR_CN
                  value: "rca-org1"
                - name: FABRIC_CA_SERVER_CSR_HOSTS
                  value: "172.17.0.2,172.17.0.3,0.0.0.0,rca-org1.hlf"
                - name: FABRIC_CA_SERVER_DEBUG
                  value: "true"
                - name: FABRIC_CA_SERVER_CA_CERTFILE
                  value: "/tmp/secrets/cert.pem"
                - name: FABRIC_CA_SERVER_CA_KEYFILE
                  value: "/tmp/secrets/key.pem"
            volumes:
              - name: scripts
                hostPath:
                  path: /mnt/hyperledger/scripts
              - name: cert
                secret:
                  secretName: cert.rca-org1
              - name: key
                secret:
                  secretName: key.rca-org1
---
apiVersion: v1
kind: Service
metadata:
  name: rca-org1
  namespace: hlf
  labels:
    app: rca-org1
spec:
  type: NodePort
  selector:
    app: rca-org1
  ports:
    - protocol: TCP
      nodePort: 30907
      targetPort: 7054
      port: 7054