apiVersion: batch/v1
kind: Job
metadata:
  name: enroll-orderer-org0
  namespace: hlf
  labels:
    app: enroll-orderer
spec:
  template:
    spec:
      containers:
        - name: fabric-ca
          image: hyperledger/fabric-ca:1.4.7
          imagePullPolicy: IfNotPresent
          command: ["bash", "./tmp/hyperledger/scripts/startNetwork/enrollJobs/enrollOrdererOrg0.sh"]
          volumeMounts:
            - mountPath: /tmp/hyperledger/scripts
              name: scripts
            - mountPath: /tmp/hyperledger/org0
              name: org0-mount
            - mountPath: /tmp/secrets/tls-ca
              name: tls-ca-cert
              readOnly: true
            - mountPath: /tmp/secrets/rca-org0
              name: rca-org0-cert
              readOnly: true
          env:
            - name: FABRIC_CA_SERVER_DEBUG
              value: "true"
      volumes:
        - name: org0-mount
          hostPath:
            path: /mnt/hyperledger/org0/
        - name: scripts
          hostPath:
            path: /mnt/hyperledger/scripts
        - name: tls-ca-cert
          secret:
            secretName: cert.tls-ca
        - name: rca-org0-cert
          secret:
            secretName: cert.rca-org0
      restartPolicy: Never
