name: Deployment test
on:
  # daily at 00:00
  schedule:
    - cron: '0 0 * * *'
  # manual triggers (can be parameterized later)
  workflow_dispatch:
  # push
  push:
    branches:
      - master
      - develop
      - feature/read_chaincode_version_from_jar
    paths-ignore:
      - README.md
      - LICENSE
      - CHANGELOG.md
  # pull request
  pull_request:
    branches:
      - master
      - develop
jobs:
  test:
    continue-on-error: [true]
    runs-on: ubuntu-latest
    name: Test network on kind
    strategy:
        matrix:
            we_just_want_to_repeat: [1, 2, 3, 4, 5]
        fail-fast: [false]
    steps:
      - uses: actions/checkout@v2

      - name: Create folder for mounts of default cluster
        run: |
          sudo mkdir -p /data/development/hyperledger
          sudo chmod -R 777 /data/development

      - name: Start KinD with default cluster config
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.7.0"
          config: assets/kind.yaml

      - name: (Temporary) install faketime to prevent clockdrifts
        run:
          sudo apt-get install faketime

      - name: Deploy network using deployment script
        run:
          ./deploy.sh -b v0.12.3
