name: Deployment test
on:
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - README.md
      - LICENSE
      - CHANGELOG.md
  pull_request:
    branches:
      - master
      - develop
jobs:
  job1:
    runs-on: ubuntu-latest
    name: Test network on Minikube
    steps:
      - uses: actions/checkout@v2
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Create folder for mounts
        run: |
          source ./env.sh
          sudo mkdir -p $HL_MOUNT
          sudo chmod -R 777 $K8S_MOUNT
      - name: Generate files from templates
        run:
          ./scripts/setMountFolder.sh
      - name: Setup mounts for minikube
        run :
          ./setupMinikube.sh
      - name: Start Network
        run:
          ./startNetwork.sh
      - name: Check Network
        run: kubectl get all -n hlf-production-network
      - name: Install Chaincode
        run:
          ./installChaincode.sh

  job2:
    runs-on: ubuntu-latest
    name: Test network on KinD
    steps:
      - uses: actions/checkout@v2
      - name: Create folder for mounts
        run: |
          source ./env.sh
          sudo mkdir -p $HL_MOUNT
          sudo chmod -R 777 $K8S_MOUNT
      - name: Generate files from templates
        run:
          ./scripts/setMountFolder.sh
      - name: Start KinD
        uses: engineerd/setup-kind@v0.4.0
        with:
          version: "v0.7.0"
          config: kind.yaml
      - name: Start Network
        run:
          ./startNetwork.sh
      - name: Check Network
        run: kubectl get all -n hlf-production-network
      - name: Install Chaincode
        run:
          ./installChaincode.sh
