name: Deployment test
on:
  # daily at 00:00
  schedule:
    - cron: '0 0 * * *'
  # manual triggers (can be parameterized later)
  workflow_dispatch:
  # push
  push:
    branches:
      - master
      - develop
    paths-ignore:
      - README.md
      - LICENSE
      - CHANGELOG.md
  # pull request
  pull_request:
    branches:
      - master
      - develop
jobs:
  job1:
    runs-on: ubuntu-latest
    name: Test network on kind
    steps:
      - uses: actions/checkout@v2

      - name: Create folder for mounts of default cluster
        run: |
          sudo mkdir -p /data/development/hyperledger
          sudo chmod -R 777 /data/development

      - name: Start KinD with default cluster config
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.7.0"
          config: assets/kind.yaml

      - name: (Temporary) install faketime to prevent clockdrifts
        run:
          sudo apt-get install faketime

      - name: Deploy network using deployment script
        run:
          ./deploy.sh
  job2:
    runs-on: ubuntu-latest
    name: Test network on kind
    steps:
      - uses: actions/checkout@v2
      - name: Create folder for mounts of default cluster
        run: |
          sudo mkdir -p /data/development/hyperledger
          sudo chmod -R 777 /data/development
      - name: Start KinD with default cluster config
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.7.0"
          config: assets/kind.yaml
      - name: (Temporary) install faketime to prevent clockdrifts
        run:
          sudo apt-get install faketime
      - name: Deploy network using deployment script
        run:
          ./deploy.sh
  job3:
    runs-on: ubuntu-latest
    name: Test network on kind
    steps:
      - uses: actions/checkout@v2
      - name: Create folder for mounts of default cluster
        run: |
          sudo mkdir -p /data/development/hyperledger
          sudo chmod -R 777 /data/development
      - name: Start KinD with default cluster config
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.7.0"
          config: assets/kind.yaml
      - name: (Temporary) install faketime to prevent clockdrifts
        run:
          sudo apt-get install faketime
      - name: Deploy network using deployment script
        run:
          ./deploy.sh
  job4:
    runs-on: ubuntu-latest
    name: Test network on kind
    steps:
      - uses: actions/checkout@v2
      - name: Create folder for mounts of default cluster
        run: |
          sudo mkdir -p /data/development/hyperledger
          sudo chmod -R 777 /data/development
      - name: Start KinD with default cluster config
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.7.0"
          config: assets/kind.yaml
      - name: (Temporary) install faketime to prevent clockdrifts
        run:
          sudo apt-get install faketime
      - name: Deploy network using deployment script
        run:
          ./deploy.sh
  job5:
    runs-on: ubuntu-latest
    name: Test network on kind
    steps:
      - uses: actions/checkout@v2
      - name: Create folder for mounts of default cluster
        run: |
          sudo mkdir -p /data/development/hyperledger
          sudo chmod -R 777 /data/development
      - name: Start KinD with default cluster config
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.7.0"
          config: assets/kind.yaml
      - name: (Temporary) install faketime to prevent clockdrifts
        run:
          sudo apt-get install faketime
      - name: Deploy network using deployment script
        run:
          ./deploy.sh
